INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Potato Salad", "Food", 5, "January 5", "January 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Vacation", "Leisure", 5000, "February 27", "April 1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bills", "Living", 2000, "January 20", "February 11");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hospital", "Medical", 30000, "June 4", "August 12");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Birthday", "Leisure", 10000, "July 25", "September 23");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Car", "Living", 1200, "October 22", "December 10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Honeymoon", "Leisure", 7000, "March 5", "May 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Funeral", "Living", 8000, "May 4", "June 1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dinner Date", "Food", 500, "August 20", "October 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Christmas Gifts", "Living", 5000, "October 30", "December 20");

INSERT INTO users (name, age) VALUES ("Josh", 28);
INSERT INTO users (name, age) VALUES ("Abigail", 22);
INSERT INTO users (name, age) VALUES ("Ben", 29);
INSERT INTO users (name, age) VALUES ("Carol", 54);
INSERT INTO users (name, age) VALUES ("Dee", 44);
INSERT INTO users (name, age) VALUES ("Evelyn", 62);
INSERT INTO users (name, age) VALUES ("Frank", 52);
INSERT INTO users (name, age) VALUES ("Gerald", 57);
INSERT INTO users (name, age) VALUES ("Hank", 18);
INSERT INTO users (name, age) VALUES ("Isabelle", 31);
INSERT INTO users (name, age) VALUES ("Jocelin", 11);
INSERT INTO users (name, age) VALUES ("Kim", 28);
INSERT INTO users (name, age) VALUES ("Liz", 28);
INSERT INTO users (name, age) VALUES ("Manny", 33);
INSERT INTO users (name, age) VALUES ("Nancy", 55);
INSERT INTO users (name, age) VALUES ("Oprah", 99);
INSERT INTO users (name, age) VALUES ("Penny", 38);
INSERT INTO users (name, age) VALUES ("Rasha", 30);
INSERT INTO users (name, age) VALUES ("Steve", 34);
INSERT INTO users (name, age) VALUES ("Tom", 37);

INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 13, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 19, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 10, 10);
